{% set info = load_file_data("iotaa/resources/info.json") %}

package:
  name: iotaa
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  build:
    - pip
  host:
    - python
    - setuptools
test:
  requires:
    - black 24.10.*
    - coverage 7.6.*
    - docformatter 1.7.*
    - isort 5.13.*
    - mypy 1.13.*
    - pylint 3.13.*
    - pytest 8.3.*
about:
  home: https://github.com/maddenp/iotaa
  license: APACHE
