{% set info = load_file_data("iotaa/resources/info.json") %}
{% set minpy = "3.10" %}

package:
  name: iotaa
  version: {{ info["version"] }}
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: {{ info["buildnum"] }}
requirements:
  host:
    - pip
    - python {{ minpy }}
    - setuptools
  run:
    - python >={{ minpy }}
test:
  requires:
    - docformatter 1.7.*
    - jq 1.8.*
    - m4 1.4.*
    - mypy 1.18.*
    - pyfakefs 5.10.*
    - pytest 9.0.*
    - pytest-cov 7.0.*
    - pytest-xdist 3.8.*
    - python {{ minpy }}
    - ruff 0.14.*
about:
  home: https://github.com/maddenp/iotaa
  license: APACHE
