package:
  name: iotaa
  version: 0.3.0
source:
  path: ../src
build:
  include_recipe: false
  noarch: python
  number: 0
requirements:
  build:
    - pip
  host:
    - python
test:
  requires:
    - black
    - coverage
    - docformatter
    - isort
    - mypy
    - pylint
    - pytest
about:
  home: https://github.com/maddenp/iotaa
  license: APACHE
