#!/bin/bash -eux

url=https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Miniforge3-Linux-x86_64.sh
wget --no-verbose $url
bash $(basename $url) -bfp conda
(
  set -e +ux
  source conda/etc/profile.d/conda.sh
  conda activate
  conda install -q -y -c maddenp --repodata-fn repodata.json anaconda-client condev python-build twine
)
