#!/bin/bash -eux

url=https://github.com/conda-forge/miniforge/releases/download/23.11.0-0/Miniforge3-23.11.0-0-Linux-x86_64.sh
wget --no-verbose $url
bash $(basename $url) -bfp conda
(
  set -e +ux
  source conda/etc/profile.d/conda.sh
  conda activate
  conda install -q -y -c maddenp --repodata-fn repodata.json anaconda-client build condev twine
)
