[tool.black]
line-length = 100

[tool.coverage.report]
fail_under = 100
show_missing = true

[tool.isort]
line_length = 100

[tool.mypy]
follow_imports = "skip"
ignore_missing_imports = true

[tool.pylint.messages_control]
disable = ["C0103", "C0104", "C0209"]
