[tool.black]
line-length = 100

[tool.coverage.report]
fail_under = 100
omit = ["*/tests/*"]
show_missing = true
skip_covered = true

[tool.docformatter]
black = true
in-place = true
make-summary-multi-line = true
pre-summary-newline = true
recursive = true
wrap-descriptions = 100
wrap-summaries = 100

[tool.isort]
line_length = 100
profile = "black"

[tool.mypy]
check_untyped_defs = true
pretty = true
warn_return_any = true

[tool.pylint.main]
extension-pkg-allow-list = []
jobs = 4
recursive = true

[tool.pylint."messages control"]
disable = [
  "broad-exception-caught",
  "consider-using-f-string",
  "disallowed-name",
  "invalid-name",
  "too-few-public-methods",
  "too-many-arguments",
  "too-many-instance-attributes",
  "too-many-positional-arguments",
  "unnecessary-lambda-assignment",
]
enable = [
  "useless-suppression",
]
